### ISSUE TITLE
不能更新cookie

### ISSUE THREAD

**Issue by S-H-Y-GitHub** [lzghzr/bilive_client#120]
Cookie失效后产生如下报错

```
Dec 19 2018 06:48:29 : shy Cookie已失效
Dec 19 2018 06:48:29 : shy Token已失效
(node:16340) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'cookies' of undefined
    at Online._update (/root/bilive_client/build/bilive/lib/app_client.js:91:54)
    at Online.login (/root/bilive_client/build/bilive/lib/app_client.js:134:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16340) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
nodejs为最新的LTS版本10.14.2，软件版本为目前最新的commit版本

**Comment by lzghzr** [comment]
#68
