### ISSUE TITLE
Error: Cannot find module '/home/ubuntu/bilive_client/build/app.js'

### ISSUE THREAD

**Issue by zhang0peter** [lzghzr/bilive_client#131]
下午git clone 后npm install时报错：
```node
> node build/app.js

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/bilive_client/build/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bilive_client@2.0.2 start: `node build/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bilive_client@2.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-17T05_43_04_624Z-debug.log

```
log文件如下：
```js
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bilive_client@2.0.2~prestart: bilive_client@2.0.2
6 info lifecycle bilive_client@2.0.2~start: bilive_client@2.0.2
7 verbose lifecycle bilive_client@2.0.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle bilive_client@2.0.2~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/bilive_client/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle bilive_client@2.0.2~start: CWD: /home/ubuntu/bilive_client
10 silly lifecycle bilive_client@2.0.2~start: Args: [ '-c', 'node build/app.js' ]
11 silly lifecycle bilive_client@2.0.2~start: Returned: code: 1  signal: null
12 info lifecycle bilive_client@2.0.2~start: Failed to exec start script
13 verbose stack Error: bilive_client@2.0.2 start: `node build/app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid bilive_client@2.0.2
15 verbose cwd /home/ubuntu/bilive_client
16 verbose Linux 4.15.0-1033-raspi2
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error bilive_client@2.0.2 start: `node build/app.js`
22 error Exit status 1
23 error Failed at the bilive_client@2.0.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by tzhongyan** [comment]
```js
> node build/app.js
```
这不是`npm install`吧？

标题报错中应该是因为未编译导致`build/`文件夹里没有`app.js`，建议`npm install && npm build`

**Comment by zhang0peter** [comment]
我直接npm install && npm start，应该是npm install &&npm run build && npm start
