### ISSUE TITLE
路径是不是还有问题？

### ISSUE THREAD

**Issue by BenZinaDaze** [lzghzr/bilive_client#24]
module.js:487
    throw err;
    ^

Error: Cannot find module '/root/bilive_client/bilive/index'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/bilive_client/app.ts:1:78)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by lzghzr** [comment]
你用的 node app.ts 吗？

**Comment by BenZinaDaze** [comment]
没问题了。昨天不小心下成源码了
