### ISSUE TITLE
有关文件配置的一些问题

### ISSUE THREAD

**Issue by Jovy310** [lzghzr/bilive_client#31]
请问文件配置在哪里配置？
是需要我将个人信息都配置在options.default.json？
另外，
地址：https://lzghzr.github.io/bilive_client_view/index.html
这里面配置的是什么？是不是有个服务器端的部署？

**Comment by lzghzr** [comment]
按照步骤做，运行到"已监听 :10080"就可以打开这个地址进行配置了，默认protocol为"admin"
另有人反应Firefox无法连接，需要chrome

Jovy310 <notifications@github.com> 于 2017年12月4日周一 19:17写道：

**Comment by Jovy310** [comment]
F:\bilive_client\bilive\index.js:13
    async Start() {
          ^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\bilive_client\app.js:2:16)
    at Module._compile (module.js:570:32)

已经安装Node.js，下载bilive_client.zip，运行了npm install，运行node app.js的时候报错。

**Comment by lzghzr** [comment]
nodejs版本需要大于8.5

Jovy310 <notifications@github.com> 于 2017年12月4日周一 19:36写道：

**Comment by Jovy310** [comment]
感激不尽
