### ISSUE TITLE
请问如何在远程管理挂机。

### ISSUE THREAD

**Issue by Fireblossom** [lzghzr/bilive_client#32]
我在vps上挂的程序，想在本地访问设置界面。可能是因为我运行了nginx和别的签到站什么的，在设置网页输入： wx://vps地址:10080 这样是连不上的，请问我如何可以(能不能)实现远程控制呢？

感谢作者大大。

**Comment by Fireblossom** [comment]
另外firefox不能访问管理界面的问题建议在readme里讲一下，我在close的issue里翻了半天才找到我用不了的原因QAQ

**Comment by diaosimiao** [comment]
@Fireblossom 我先声明我不懂这些编程技术，纯粹门外汉。
我一般用笨点的办法，options/options.json文件本地直接软件编辑好或者网页设置好再传上去。
别笑我。

**Comment by Fireblossom** [comment]
@diaosimiao 你和我现在远程桌面连接的方法没区别，同笨同笨哈哈哈哈
不过如果远程设置/控制(类似asf的--server模式)能做到的话，我腾讯云学生机就重装一个linux了

**Comment by liansishen** [comment]
options.json 文件里的hostname改成vps的IP地址
再本地打开index.html，连接ws://vps地址:10080就可以了
Firefox57设置页面可以正常运行

**Comment by Fireblossom** [comment]
@liansishen 感谢帮助，但是我这里出现了如下错误

C:\Users\Administrator\Desktop\bilive_client>node app.js
Dec 06 2017 02:01:51 : { Error: listen EADDRNOTAVAIL 我的ip:10080
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1523:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
  errno: 'EADDRNOTAVAIL',
  code: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '我的ip',
  port: 10080 }

**Comment by lzghzr** [comment]
要外网可以访问需要监听0.0.0.0，默认应该是开启的，windows系统可能需要配置一下防火墙，放行10080端口。
并且，由于密码都是未加密传输的(因为需要明文密码进行登录，不太可能进行加密)，为了提高安全性最好用Nginx套一个ssl，使用wss(对应https)，这也是为什么火狐不能连接的原因(https页面不允许ws协议)

Fireblossom <notifications@github.com> 于 2017年12月6日周三 02:06写道：

**Comment by liansishen** [comment]
@Fireblossom 
我是在内网树莓派上搭的，直接设置内网IP就可以了
外网访问看作者的回复来设置吧

**Comment by Fireblossom** [comment]
@lzghzr 按照您的指导我设置好了，非常感谢
也非常感谢@liansishen 的帮助

**Comment by catbule** [comment]
请问是怎么解决了，我在Ubuntu也遇到了同样的错误

**Comment by Fireblossom** [comment]
@catbule 在hostname里填0.0.0.0即可。
然后nginx设置反代不会的话也可以问我。

**Comment by catbule** [comment]
@Fireblossom 怎么联系你- -

**Comment by Fireblossom** [comment]
@catblue 直接在这问就好_(:з」∠)_

**Comment by Fireblossom** [comment]
@catbule 直接这里问就行~

**Comment by catbule** [comment]
@Fireblossom 

Dec 11 2017 19:50:58 : { Error: listen EADDRNOTAVAIL 我的IP:10080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '我的IP',
  port: 10080 }
^Croot@VM-131-68-debian:~/bilive_client# npm start

> bilive_client@1.2.5 start /root/bilive_client
> node app.js

Dec 11 2017 19:53:41 : 已监听 0.0.0.0:10080
Dec 11 2017 19:55:43 : 房间 71084 赠送了第 374


设置成0.0.0.0后还是不能远程连接，是必须要反代之后才能连接吗

**Comment by Fireblossom** [comment]
如果没有套nginx的话，打开设置界面输入
ws://你的IP:10080
即可

**Comment by catbule** [comment]
@Fireblossom 不行，连接失败

**Comment by Fireblossom** [comment]
@catbule 看看端口开放了没

**Comment by catbule** [comment]
@Fireblossom 谢谢，已经解决了。
刚才突发奇想用Windows server链接Ubuntu，成功了，看来是我宿舍的网络被限制了

**Comment by Fireblossom** [comment]
@catbule 建议套个nginx，一个是套ssl安全，一个是实际上wss走443端口不会屏蔽
