### ISSUE TITLE
大大我的这个是什么问题。

### ISSUE THREAD

**Issue by selfler** [lzghzr/bilive_client#35]
at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1496:7)
    at Options._HttpServer (/home/wwwroot/bilive_client/bilive/options.js:28:20)
    at Options.Start (/home/wwwroot/bilive_client/bilive/options.js:15:14)
    at BiLive.Options (/home/wwwroot/bilive_client/bilive/index.js:29:18)
    at BiLive.Start (/home/wwwroot/bilive_client/bilive/index.js:22:18)
    at <anonymous>
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 10080 }
昨天还行
node 9.2.0

**Comment by lzghzr** [comment]
端口被占用，看看是不是你已经开了一个了

selfler <notifications@github.com> 于 2017年12月7日周四 21:47写道：

**Comment by selfler** [comment]
好了。。旧版本开了个窗口忘记了😂
