### ISSUE TITLE
网络状况不佳时，程序会崩溃退出

### ISSUE THREAD

**Issue by S-H-Y-GitHub** [lzghzr/bilive_client#56]
控制台信息：

```
Jan 28 2018 20:59:27 : 尝试重连弹幕服务器失败，五分钟后再次重新连接
Jan 28 2018 21:02:30 : http://api.live.bilibili.com/YunYing/roomEvent?event_type=newspring-4539&room_id=939654&access_key=45f10954ee61e618be0652bd9d37fa16&actionKey=appkey&appkey=1d8b6e7d45233436&build=521200&mobi_app=android&platform=android&ts=1517144069&sign=eb6c0e0e5e28ec9e2fef2a2cc1c89240 { Error: read ECONNABORTED
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNABORTED', errno: 'ECONNABORTED', syscall: 'read' }
Jan 28 2018 21:02:30 : http://api.live.bilibili.com/User/userOnlineHeart { Error: read ECONNABORTED
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNABORTED', errno: 'ECONNABORTED', syscall: 'read' }
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ENETUNREACH 101.200.58.11:80 - Local (0.0.0.0:0)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at emitLookup (net.js:1106:7)
    at options.lookup (/data/data/com.termux/files/home/bilive_client/bilive/lib/tools.js:50:24)
    at lookupAndConnect (net.js:1087:3)
    at Socket.connect (net.js:1028:5)
    at Object.connect (net.js:103:35)
    at Agent.IP.httpAgent.createConnection (/data/data/com.termux/files/home/bilive_client/bilive/lib/tools.js:52:24)
    at Agent.createSocket (_http_agent.js:237:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bilive_client@1.3.3 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bilive_client@1.3.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

[2018-01-28T13_02_30_711Z-debug.log](https://github.com/lzghzr/bilive_client/files/1671142/2018-01-28T13_02_30_711Z-debug.log)

**Comment by lzghzr** [comment]
恩了解了，以及accesskey不要发出来

率怀一 <notifications@github.com> 于 2018年1月28日周日 22:18写道：
