### ISSUE TITLE
不知道这是什么情况 index进不去

### ISSUE THREAD

**Issue by Naexen** [lzghzr/bilive_client#58]
找不到报错 从旧电脑上copy来的能打开能每日签到 index点链接显示连接失败 powershell界面没有链接提示，重新下载之后走一遍流程会在已监听10080这里卡住。不知道为啥我这里传不了图emmm'

**Comment by lzghzr** [comment]
连不上可以按F12看一下控制台报错

**Comment by Naexen** [comment]
SCRIPT12029: SCRIPT12029: WebSocket Error: Network Error 12029, 无法与服务器建立连接

**Comment by Naexen** [comment]
抽奖时断时续的 PS C:\Users\Administrator\Desktop\bilive_client> npm start

> bilive_client@1.3.2 start C:\Users\Administrator\Desktop\bilive_client
> node app.js

Feb 21 2018 00:29:11 : 正在测试可用ip
Feb 21 2018 00:29:13 : 可用ip数量为 34
Feb 21 2018 00:29:16 : 已监听 :10080
走到这里之后直接就开始签到了

**Comment by Naexen** [comment]
Feb 21 2018 00:33:31 : http { Error: listen EADDRINUSE :::10080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Options._HttpServer (C:\Users\Administrator\Desktop\bilive_\bilive\options.js:29:20)
    at Options.Start (C:\Users\Administrator\Desktop\bilive_\bilive\options.js:16:14)
    at BiLive.Start (C:\Users\Administrator\Desktop\bilive_\bilive\index.js:27:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 10080 }

重新下了一遍的报错

**Comment by diaosimiao** [comment]
链接不上可能防火墙问题 大佬的程序还是很牛逼的，一直稳定。
谢谢lzghzr 大佬~

**Comment by lzghzr** [comment]
EADDRINUSE
断端口被占用

**Comment by Naexen** [comment]
怎么解决啊 换端口吗

**Comment by Naexen** [comment]
怎么换呐qwq

**Comment by lzghzr** [comment]
手动设置options.json可以改端口

**Comment by Naexen** [comment]
Feb 23 2018 12:42:34 : JSONparse SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at JSONparse.resolve (C:\Users\Administrator\Desktop\bilive_\bilive\lib\tools.js:168:30)
    at new Promise (<anonymous>)
    at JSONparse (C:\Users\Administrator\Desktop\bilive_\bilive\lib\tools.js:166:12)
    at Options.Promise (C:\Users\Administrator\Desktop\bilive_\bilive\lib\tools.js:131:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
(node:456) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: 文件 格式化失败
(node:456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lzghzr** [comment]
文件 格式化失败 嘛，字面意思，json格式不正确

**Comment by youyoudeminger** [comment]
我想问一下，就是电脑端的高能抽奖有没有延迟，如果有的话在哪改

**Comment by lzghzr** [comment]
@youyoudeminger 没有延迟，大致流程，B站弹幕发出全屏公告，获取房间抽奖信息，加入抽奖
想要降低延迟尽量快就可以了，比如挑选最快的弹幕节点，最快的CDN节点，或者你知道B站的服务器ip从而不用CDN中转，都可以提高速度
或者你知道B站bug可以提前参与抽奖也是可以的（这个bug以前还真有，最近没研究过
