### ISSUE TITLE
运行node app.js 出错

### ISSUE THREAD

**Issue by pwd0755** [lzghzr/bilive_client#8]
module.js:457
    throw err;
    ^

Error: Cannot find module '/root/node-v6.4.0/bilive_client/app.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by lzghzr** [comment]
试了一下没有问题，看报错应该时路径的原因，检查一下

**Comment by pwd0755** [comment]
重新安装了几次 都是报错

**Comment by lzghzr** [comment]
你是在什么环境下运行的？

**Comment by pwd0755** [comment]
debian7 64安装的node6.4.0

**Comment by lzghzr** [comment]
没有任何问题
![putty_2017-07-29_21-00-21](https://user-images.githubusercontent.com/13391314/28745018-3570286a-74a1-11e7-9d79-7cdc49a2d49a.png)

**Comment by pwd0755** [comment]
还是不行
root@123:~/bilive_client# /usr/local/bin/node app.js
module.js:457
    throw err;
    ^

Error: Cannot find module '/root/bilive_client/app.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by pwd0755** [comment]
是不是除了node 还需要装其他的东西？

**Comment by lzghzr** [comment]
才发现，哥们，你是不是没解压也没运行npm install就开始node app.js了
我简介里一共就五句话，你漏掉了两句

**Comment by pwd0755** [comment]
感谢 已经能用了
